[build]
  command = "./build.sh"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/kendricktan/ingredients"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ingredients/:splat"
  status = 200